const TIPO_INSTRUCCION = {
    COUT: 'INST_COUT',
    DECLARACION: 'DECLARACION',
    ASIGNACION: 'ASIGNACION',
    WHILE: 'WHILE',
    DEC_METODO: 'DEC_METODO',
    EXEC: 'EXEC',
    LLAMADA_METODO: 'LLAMADA_METODO',
    IF: 'IF',
    IFCE: 'IFCE',
    IFCEIF: 'IFCEIF',
    ELSEIF: 'ELSEIF',
    BREAK: 'BREAK',
    SWITCH: 'SWITCH',
    CASE:   'CASE',
    DEFAULT: 'DEFAULT',
    RETURN: 'RETURN',
    CONTINUE: 'CONTINUE',
    DO_WHILE: 'DO_WHILE',
    FOR:        'FOR',
    MODIFICAR_VECTOR: 'MODIFICAR_VECTOR',
    AGREGAR_LISTA: 'AGREGAR_LISTA',
    DEC_FUNCION: 'DEC_FUNCION',
    DECLARACIONTOCHAR: 'DECLARACIONTOCHAR'
}

module.exports = TIPO_INSTRUCCION