const TIPO_VALOR={
    ENTERO:         'VAL_ENTERO',
    DECIMAL:       'VAL_DECIMAL',
    CADENA:        'VAL_CADENA',
    BANDERA:       'VAL_BANDERA',
    IDENTIFICADOR: 'VAL_IDENTIFICADOR',
    VECTOR: 'VAL_VECTOR',
    LISTA: 'VAL_LISTA'   
}

module.exports = TIPO_VALOR